<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac.Configuration" Version="7.0.0" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="NLog" Version="6.1.1" />
        <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.2" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CRTVUP.Unify.Common.ShortLink.DomainService\CRTVUP.Unify.Common.ShortLink.DomainService.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Logs\Error\" />
      <Folder Include="Logs\Info\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
