<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Idler.Common.Autofac" Version="0.3.0.1" />
        <PackageReference Include="Idler.Common.EntityFrameworkCore" Version="0.3.0.1" />
        <PackageReference Include="Idler.Common.AutoMapper" Version="0.3.0.1" />
        <PackageReference Include="Idler.Common.Cache.FreeRedis" Version="0.3.0.1" />
        <ProjectReference Include="..\CRTVUP.Unify.Common.ShortLink.Abstractions\CRTVUP.Unify.Common.ShortLink.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
