<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Idler.Common.Autofac" Version="0.2.0.1" />
        <PackageReference Include="Idler.Common.EntityFrameworkCore" Version="0.2.0.1" />
        <PackageReference Include="Idler.Common.AutoMapper" Version="0.2.0.1" />
        <PackageReference Include="Idler.Common.Cache.FreeRedis" Version="0.2.0.1" />
        <ProjectReference Include="..\SimpleMicroService.Abstractions\SimpleMicroService.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup Condition="'$(PostgreSQL)' == 'True' ">
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    </ItemGroup>
    <ItemGroup Condition="'$(MySQL)' == 'True' ">
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
